#!/bin/bash
# Usage examples for linear_classifier.py

echo "=== LINEAR CLASSIFIER USAGE GUIDE ==="
echo ""

# Basic usage example
echo "1. BASIC USAGE:"
echo "python linear_classifier.py --input_embs /path/to/dataset"
echo ""

# With different scenarios
echo "2. DIFFERENT BAND COMBINATIONS:"
echo "# Use concatenated bands (g+r)"
echo "python linear_classifier.py --input_embs /path/to/dataset --scenario concat"
echo ""
echo "# Use averaged bands (mean of g and r)"
echo "python linear_classifier.py --input_embs /path/to/dataset --scenario avg"
echo ""
echo "# Use only g band"
echo "python linear_classifier.py --input_embs /path/to/dataset --scenario g"
echo ""
echo "# Use only r band"  
echo "python linear_classifier.py --input_embs /path/to/dataset --scenario r"
echo ""

# With different datasets
echo "3. DIFFERENT DATASETS:"
echo "# Moirai dataset (FAST - 30 time steps)"
echo "python linear_classifier.py \\"
echo "  --input_embs /projects/b1094/StarEmbed/embeddings/descriptive_name_embeddings/csdr1_raw_embs_moiral_small_trn_val_tst_ctx200_pdt64_psz16_bandgr \\"
echo "  --scenario concat"
echo ""
echo "# T5 dataset (SLOW - 201 time steps)"
echo "python linear_classifier.py \\"
echo "  --input_embs /projects/b1094/StarEmbed/embeddings/descriptive_name_embeddings/csdr1_raw4_catflags_filtered_embs_chronos_t5_tiny_trn_val_tst_ctx200_bandgr \\"
echo "  --scenario avg"
echo ""

# Advanced options
echo "4. ADVANCED OPTIONS:"
echo "# Custom output directory and kNN parameter"
echo "python linear_classifier.py \\"
echo "  --input_embs /path/to/dataset \\"
echo "  --scenario concat \\"
echo "  --k 10 \\"
echo "  --seed 123"
echo ""

# Performance modes
echo "5. PERFORMANCE MODES:"
echo ""
echo "🚀 ULTRA FAST MODE (if combined_embedding exists):"
echo "   → Run compute_avg_embeddings.py first to add combined_embedding column"
echo "   → Then linear_classifier.py will automatically use it (10x+ speedup!)"
echo ""
echo "⚠️  FALLBACK MODE (if combined_embedding missing):"
echo "   → linear_classifier.py will compute embeddings on-the-fly (slower)"
echo "   → Still works, but much slower for large datasets"
echo ""

echo "6. STEP-BY-STEP WORKFLOW:"
echo ""
echo "# Step 1: Add combined_embedding for maximum speed"
echo "python compute_avg_embeddings.py \\"
echo "  --dataset csdr1_raw_embs_moiral_small_trn_val_tst_ctx200_pdt64_psz16_bandgr \\"
echo "  --band_combination concat"
echo ""
echo "# Step 2: Run classification (ULTRA FAST!)"
echo "python linear_classifier.py \\"
echo "  --input_embs /projects/b1094/StarEmbed/embeddings/descriptive_name_embeddings/csdr1_raw_embs_moiral_small_trn_val_tst_ctx200_pdt64_psz16_bandgr \\"
echo "  --scenario concat"
echo ""

echo "7. OUTPUT:"
echo "Results saved to: /projects/b1094/StarEmbed/src/output/linear_classification/new_avg_embedding/"
echo "- logistic_metrics_report.csv  (classification metrics)"
echo "- logistic_confusion.pkl       (confusion matrix)"
echo "- logistic_confusion.pdf       (confusion matrix heatmap)"
echo "- knn_metrics_report.csv       (kNN metrics)"
echo "- knn_confusion.pkl            (kNN confusion matrix)"
echo "- knn_confusion.pdf            (kNN confusion matrix heatmap)"
echo ""

echo "8. AVAILABLE DATASETS:"
echo "# List all available datasets"
echo "ls /projects/b1094/StarEmbed/embeddings/descriptive_name_embeddings/"
